stridera/fierymud

src/magic.cpp
src/rooms.cpp
src/vsearch.cpp
src/weather.cpp

Found a few additional stray &9's without &b.  Updated so they'll be visible.

additional color corrections for &9

---

src/magic.cpp

Priority 1 - unable to build otherwise.

fixed an error with a random number generator

---

src/skills.cpp

Also updated documentation to clarify which value was "no_fight" and what that value means.

cure blind can be cast during combat

---

src/act.informative.cpp
src/act.offensive.cpp
src/act.other.cpp
src/spell_parser.cpp

Added numerical values to cooldown messages for all cooldowns longer than 20 seconds.
Reformatted all cooldown messages to consistently display in real time seconds.

modified cooldown messages

---

src/act.informative.cpp

Ignores both race and cooldown restrictions if over level 100

allows imms to use all innates

---

include/defines.hpp
include/messages.hpp
src/constants.cpp
src/interpreter.cpp
src/messages.cpp
src/races.cpp

Major new update that allows players to read the help files on races and classes from the character creation screen.
Also updated the words we use to describe magnitude of a stat based on recent new player feedback - Fantastic, Very Good, Average (instead of Good), Not Good (instead of Fair), and Bad.  "Good" was confusing since it represented our our statistical average numbers, making players think a 74 is a "high" number.  "Below Average" is too long to replace "Fair" unfortunately.

New char menu

---

src/act.other.cpp

I thought this was already included but apparently not...

Hover slot items remain when shapechanging

---

src/magic.cpp
src/spells.cpp

- Add a check of caster skill vs. target level
- Creatures immune to charm are now immune to paralysis
- Spell messages are now more creative than just "PARALYZE!"

Nerf power of Major Paralysis

---

src/act.item.cpp
src/act.other.cpp

Realized this is going to be an equipment duplication exploit I forgot to patch!

Prevent players from removing gear while shapechanged

---

src/class.cpp
src/races.cpp
src/spell_mem.cpp

creates class focus factor

---

src/magic.cpp

Fixes bug I created back in July.

stops mobs from casting buffs infinitely

---

src/act.informative.cpp

fixes crash on IDing weapons

---

include/shop.hpp
src/act.other.cpp
src/interpreter.cpp
src/shop.cpp
src/spec_procs.cpp

This is one we've been hoping for for a while!  Creates the ability to ID items in shops for 10% of the purchase price.

Creates Inspect command to ID items in shops

---

src/act.informative.cpp
src/act.wizinfo.cpp

Adds location of carrying/wearing mobs and containers to where and olocate

---

include/fight.hpp
src/act.informative.cpp
src/act.offensive.cpp
src/fight.cpp

Breaks the displacement effect into a separate function and spreads it to most single-target skills.

Displaced function

---

src/magic.cpp
src/spell_parser.cpp

Made the following spells refreshable:
Feather Fall
Magic Torch
Gaia's Cloak
Circle of Light
Negate Cold
Negate Heat

Adjust refresh spells

---

include/defines.hpp
include/events.hpp
include/interpreter.hpp
src/comm.cpp
src/events.cpp
src/interpreter.cpp

Creates a 5 minute timer to create a name which refreshes on prompt.
Creates a 30 second timer to create a password which also refreshes on prompt.

Creates new login timers

---

src/spell_parser.cpp

So imms don't just get blank lines when they try to perform too much

creates imm bypass for perform limits

---

include/ai.hpp
src/act.other.cpp
src/ai_utils.cpp
src/cleric.cpp
src/dg_scripts.cpp
src/rogue.cpp
src/sorcerer.cpp
src/spell_parser.cpp

Updates 'group_size' script variable to always show the group size.
Created 'group_size_in_room' to show how many are actually in the room with you.

Group size

---

src/fight.cpp
src/magic.cpp

Remove class AI from illusions and prevent them from being able to attack their creators

---

include/act.hpp
src/act.informative.cpp
src/string_utils.cpp

Also remove the text message telling you that you suck.

Fix case where skill is greater than level max

---

src/act.offensive.cpp

Also fixed an unseen hitall bug.

fixed roundhouse from crashing the game

---

src/act.offensive.cpp

Previous version of Roundhouse skill attempted to route the function through do_kick - only problem was it needed to identify the target based on an argument, which was causing it to attack the same target once for every mob with the same name in the room, rather than rolling through the list.  Had to duplicate some of the do_kick code in do_roundhouse instead and make it a unique command to work correctly.

fixes targets for roundhouse

---

src/act.offensive.cpp
src/damage.cpp
src/fight.cpp

Ended up having to modify the radiant damage evasion code to make this work 100% correctly too, but now monk energy types apply properly to kick attacks.

fixed energy on kick attacks

---

src/act.other.cpp

just added some color to the 'tried to steal' message.

update steal message with color

---

src/act.other.cpp

updating the other steal message too

message update 2
