stridera/fierymud

src/races.cpp
I made this change to help with writing triggers.  This way the script can check for half_elf instead of half-elf, which will ease the burden of matching mob race.
=> changed punctuation in a half-elf field

src/fight.cpp
Any command going through the hit function in fight.cpp now checks for guard.
=> added guard check to all hits

src/fight.cpp
Not sure when this was implemented, but it's the reason hitall and riposte were switching targets without a message.
The code at the top of fight.cpp clearly says only the set_battling function should allow targets to switch, which should be checked by switch_ok within the specific command/function that initiates the attack.
I've only commented out the code in case there's a real reason to use it so we can quickly restore and change the comments in the doc.
=> commented out code that was causing any use of hit() to switch without message

include/dg_scripts.hpp, src/act.item.cpp, src/dg_triggers.cpp
As it turns out, drop triggers already run when an item is placed in another object if the trigger is on the item being placed.  This modification expands drop triggers to run on containers when items are put into them.
It also adds the UID variable "target". 
- If the trigger running is on the **item** being placed in a container, "target" is the _container the object is placed in_.  
- If the trigger running is on the **container** an object is being place in, "target" is the _object being put in the container_.
- If an item is just being dropped, "target" is not retained.
=> drop triggers now work on containers

include/casting.hpp, include/defines.hpp, include/dg_scripts.hpp, include/interpreter.hpp, include/objects.hpp, scripts/mud/flags.py, scripts/mud/obj.py, src/act.informative.cpp, src/act.item.cpp, src/act.other.cpp, src/act.wizinfo.cpp, src/ai_utils.cpp, src/db.cpp, src/dg_scripts.cpp, src/dg_triggers.cpp, src/interpreter.cpp, src/objects.cpp, src/oedit.cpp, src/shop.cpp, src/spell_parser.cpp, src/vsearch.cpp
The "instrument" magic item is just a staff, but re-orders the action desc display flow so the action desc text is displayed to both the user and the room when it's used.  Allows for flavor text around the kind of music the instrument plays.
The "use" trigger is checked when magic items are activated.  This supplements "command" triggers by allowing us to make sure specific items are being activated (ie 3.wand).  This will be immediately used in Meteorswarm and Charm Person.  The trigger can block the use of the magic item as well.
It will also allow us to create new scrolls of recall without having to create specprocs for them, and allows us to more quickly change where players are sent when they're activated.
=> creates the instrument magic item type and a use trigger

include/defines.hpp, src/act.offensive.cpp, src/class.cpp, src/magic.cpp
- Allows Berserkers to rescue and guard, but only while berserking
- A target can be designated as guarded at any time, but guard will only intercept while berserking
- Lowered threshold to activate berserk from 500 to 100
- Added Apocalyptic Anthem to list of chants for aggro control
=> Grant berserker rescue, guard, lower berserk threshold

src/fight.cpp
This was dumb.  Why did they even do this in the first place?
=> Blinded mobs will no longer throw syslog errors when they try to attack

src/act.informative.cpp
Two changes to Identify:
- Properly displays the damage type by name, rather than index number
- As weapons could have multiple damage types now, I revised the old code to indicate if an item has a trigger or specproc without specifying what it is.  Players will now simply see "This item has hidden special properties!" if it has either a trigger or a specproc.
=> displays damage types on weapons and indicated triggers

src/magic.cpp
flamestrike can now be cast by evils
damage was ((ALIGN*.0007)+.8)
damage now((INT*.007)+.8)
=> flamestrike updates for spell-slot branch

src/magic.cpp
flamestrike can now be cast by evils
damage was ((ALIGN*.0007)+.8)
damage now((INT*.007)+.8)
=> change flamestrike from align based to INT based.

include/limits.hpp, src/comm.cpp, src/limits.cpp, src/magic.cpp
- Moves the check for eff_poison from point_update to a new function sick_update
- Disease will be moved into this function in a future pass
- sick_update checks every 6 rounds
- Poison now deals 2% of max HP in damage to NPCs but 5.88% minus Con bonus HP to PCs
- Duration reduced from (4 + 10% of skill) [min 4, max 14] to (2 + 3% of skill + 1/2 Wis Mod) [min 2, max 8]
=> Increase poison lethality

src/damage.cpp
Prevents a bug that causes mobs to composition evade backstabs from energy weapons.
=> correctly sets default damage type when backstabbing to null instead of junk number

src/fight.cpp, src/mobact.cpp
This is an attempt to fix a bug Zaver is having where his illusions are switching to him when using the kick command.
I haven't been able to reproduce, but he's showed me multiple logs where it happens.  From everything I can tell, this should prevent it from happening, though I don't know what the actual cause is because again, I can't reproduce it myself.
=> Attempts to stop illusions from attacking their masters

src/skills.cpp
With the increased pressure from Poison, Remove Poison needs to be castable in combat.
=> allows remove poison to be cast in combat

src/magic.cpp
Finally, "you are too busy casting" should be a thing of the past.
=> prevents mag_aff from setting target wait to 2

include/class.hpp, include/races.hpp, include/skills.hpp, src/act.informative.cpp, src/act.other.cpp, src/cleric.cpp, src/db.cpp, src/races.cpp, src/rogue.cpp, src/skills.cpp, src/spell_mem.cpp, src/spell_parser.cpp, src/warrior.cpp
This new system is now ready to go live!  The purpose of this enhancement is to allow us to properly assign skills and spells based on race as we develop new races.  Players should notice very little in the short-term from this update.
Special notes:
- changed IS_SPELLCASTER macro to IS_SPELLCASTER_CLASS macro and updated the define to pull directly from the ClassDef "spellcaster?" property
- added IS_SPELLCASTER_RACE macro
- added a "spellcaster?" true/false property to the RaceDef struct and updated all races and defined IS_SPELLCASTER_RACE with this property
- updated SKILL_LEVEL(ch, skillnum) macro to be the lower of class and race min level assignment
Player-facing changes:
- Dragonborn now have their breathe skill properly assigned at level 1 instead of a random low value
- Elves …
=> Race spells

include/modify.hpp, include/string_utils.hpp, src/act.informative.cpp, src/modify.cpp, src/string_utils.cpp
=> Add progress bar to skills view.

src/damage.cpp
Fixes an oversight on unblessed weapons dealing smite damage like Rahmat being unable to deal damage to ethereal composition creatures.
=> radiant weapons ignore ether composition

src/fight.cpp
There was a bug in the fight code which caused things to always deal damage, even if they should have missed the attack.
=> things can actually miss now

src/class.cpp
By lowering thac0 in this way, mobs of level 92 are no longer guaranteed to hit on every attack without extra bonuses or spells.  Players are unlikely to notice a change to their attacks because mob AC doesn't tend to increase since they lack gear, and players have a number of +hitroll bonuses they tend to use.
=> Changes thac0 on warrior types from -4/-5 to -2
